# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
### BEGIN LICENSE
# This file is in the public domain
### END LICENSE

### DO NOT EDIT THIS FILE ###

from gi.repository import Gio, Gtk # pylint: disable=E0611
import logging
logger = logging.getLogger('test_lib')

from . helpers import get_builder, show_uri, get_help_uri
import sys
sys.path.append("/home/ishaan/Desktop/cs315/project/pdf-fondler/test/db_script")
from mongodb_script import get_all
# This class is meant to be subclassed by TestWindow.  It provides
# common functions and some boilerplate.
class Window(Gtk.Window):
    __gtype_name__ = "Window"

    # To construct a new instance of this method, the following notable 
    # methods are called in this order:
    # __new__(cls)
    # __init__(self)
    # finish_initializing(self, builder)
    # __init__(self)
    #
    # For this reason, it's recommended you leave __init__ empty and put
    # your initialization code in finish_initializing
    
    def __new__(cls):
        """Special static method that's automatically called by Python when 
        constructing a new instance of this class.
        
        Returns a fully instantiated BaseTestWindow object.
        """
        builder = get_builder('TestWindow')
        new_object = builder.get_object("test_window")
        new_object.finish_initializing(builder)
        return new_object

    def finish_initializing(self, builder):
        """Called while initializing this instance in __new__

        finish_initializing should be called after parsing the UI definition
        and creating a TestWindow object with it in order to finish
        initializing the start of the new TestWindow instance.
        """
        # Get a reference to the builder and set up the signals.
        self.builder = builder
        self.ui = builder.get_ui(self, True)
        self.PreferencesDialog = None # class
        self.preferences_dialog = None # instance
        self.AboutDialog = None # class
        self.ManualMode = None #class
        self.manual_dialog=None #instance
        self.settings = Gio.Settings("net.launchpad.test")
        self.settings.connect('changed', self.on_preferences_changed)

        # Optional application indicator support
        # Run 'quickly add indicator' to get started.
        # More information:
        #  http://owaislone.org/quickly-add-indicator/
        #  https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators
        try:
            from test import indicator
            # self is passed so methods of this class can be called from indicator.py
            # Comment this next line out to disable appindicator
            self.indicator = indicator.new_application_indicator(self)
        except ImportError:
            pass

    def on_mnu_contents_activate(self, widget, data=None):
        show_uri(self, "ghelp:%s" % get_help_uri())

    def on_mnu_about_activate(self, widget, data=None):
        """Display the about box for test."""
        if self.AboutDialog is not None:
            about = self.AboutDialog() # pylint: disable=E1102
            response = about.run()
            about.destroy()
    def on_manualMode_activate(self, widget,data=None):
        # if self.manual_dialog is not None:
            # logger.debug('show existing manual_dialog')
            # self.manual_dialog.present()
        # elif self.ManualMode is not None:
        logger.debug('create new manual_dialog')
        self.manual_dialog = self.ManualMode() # pylint: disable=E1102
        # self.manual_dialog.connect('destroy', self.on_manual_dialog)
        response = self.manual_dialog.run()
        # print response
        self.manual_dialog.destroy()
        # builder = get_builder('ManualModeDialog')
        # new_object = builder.get_object("test_window")
        # treeview = builder.get_object("manualTreeview")
        # print treeview.get_cell_renderers()
        # if self.ManualMode is not None:
        #     manual = self.ManualMode() # pylint: disable=E1102
        #     response = manual.run()
        #     builder = get_builder('ManualModeDialog')
        #     treeview = builder.get_object("manualTreeview")
        #     model = builder.get_object("manualModel") #this is lisStore

        #     all_files = get_all()
        #     for file_name, page_tag_dict in all_files.iteritems(): 
        #         parent = model.append(None,[file_name,'',False])
        #         for page_num, tags in page_tag_dict.iteritems():
        #             model.append(parent,["Page "+page_num,tags,True])

        #     treeview.set_model(model)
        #     renderer = Gtk.CellRendererText()
        #     renderer.set_padding(10,20)
        #     # rendere.set_
        #     column = Gtk.TreeViewColumn('File Name',renderer, text=0)

        #     renderer1 = Gtk.CellRendererText()
        #     renderer1.set_padding(10,20)
        #     # rendere.set_
        #     column1 = Gtk.TreeViewColumn('Tags',renderer1, text=1,editable=2)
        #     # renderer1.connect('edited', cell_edited_callback,model,1)
        #     # column.set_spacing(-1)
        #     # column.set_attribute()
        #     treeview.insert_column(column,0)
        #     treeview.insert_column(column1,1)

        
    def on_mnu_preferences_activate(self, widget, data=None):
        """Display the preferences window for test."""

        """ From the PyGTK Reference manual
           Say for example the preferences dialog is currently open,
           and the user chooses Preferences from the menu a second time;
           use the present() method to move the already-open dialog
           where the user can see it."""
        if self.preferences_dialog is not None:
            logger.debug('show existing preferences_dialog')
            self.preferences_dialog.present()
        elif self.PreferencesDialog is not None:
            logger.debug('create new preferences_dialog')
            self.preferences_dialog = self.PreferencesDialog() # pylint: disable=E1102
            self.preferences_dialog.connect('destroy', self.on_preferences_dialog_destroyed)
            self.preferences_dialog.show()
        # destroy command moved into dialog to allow for a help button

    def on_mnu_close_activate(self, widget, data=None):
        """Signal handler for closing the TestWindow."""
        self.destroy()

    def on_destroy(self, widget, data=None):
        """Called when the TestWindow is closed."""
        # Clean up code for saving application state should be added here.
        Gtk.main_quit()

    def on_preferences_changed(self, settings, key, data=None):
        logger.debug('preference changed: %s = %s' % (key, str(settings.get_value(key))))

    def on_preferences_dialog_destroyed(self, widget, data=None):
        '''only affects gui
        
        logically there is no difference between the user closing,
        minimising or ignoring the preferences dialog'''
        logger.debug('on_preferences_dialog_destroyed')
        # to determine whether to create or present preferences_dialog
        self.preferences_dialog = None

    
           
    def cell_edited_callback(cell,path,model=None,col_num=0):
        print cell
        print path